### ISSUE TITLE
Roe

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/shock-cloud#1]
# Roe Riemann Solver
Dylan assigned to run several simulations using the Roe Riemann solver.

## Tasks
- [x] Run w/ Roe out-of-the-box (don't change input)
- [x] Run w/ [double resolution](https://github.com/PrincetonUniversity/athena-public-version/wiki/Modifying-the-Input-File) 
- [x] Run w/ quadruple resolution
- [x] Run w/ different mach speed
- [x] Run w/ magnetic field
- [ ] Run w/ different beta value

- [ ] High Resolution, MPI - temp, pressure, density plots
- [ ] High res MPI, w/ B field in x direction
- [ ] High res MPI, w/ diff. mach speed
- [ ] High res MPI, w/ B field and diff. beta constant

**Comment by sabaronett** [comment]
@durkedy, you might want to time your results and post them here.

**Comment by durkedy** [comment]
Ran ootb simulation using Roe Riemann solver... made density, pressure and velocity vector animations. will post to github.

**Comment by sabaronett** [comment]
@durkedy, don't forget to try a **streamline** plot of `b` in VisIt.

**Comment by sabaronett** [comment]
@durkedy, if you get a chance, can you move all your "roe_" related folders into a main folder called "roe", just to clean the root a bit?
