### ISSUE TITLE
LLF

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/shock-cloud#2]
# LLF Riemann Solver
@LazarNov assigned to run several simulations using the LLF Riemann solver.

## Tasks
- [ ] Run w/ LLF out-of-the-box (don't change input)
- [ ] Run w/ [double resolution](https://github.com/PrincetonUniversity/athena-public-version/wiki/Modifying-the-Input-File) 
- [ ] Run w/ different starting velocity

**Comment by sabaronett** [comment]
@LazarNov, don't forget to record the time, i.e., how long it took to run the simulation w/ your solver, and post the results in a comment here. Thanks.

**Comment by sabaronett** [comment]
To be addressed as part of #5.

Closing issue.
